# Generated by Django 4.1 on 2022-08-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='project',
            new_name='project_id',
        ),
    ]
