# Generated by Django 4.1 on 2022-08-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='repo_url',
        ),
    ]
